<?php


$states = [
    [
        "State_Name" => "Abia",
        "capital" => "Umuahia",
        "Mineral_Resources" => "Limestone, Kaolin, gypsum, galena, bentonite clay, gold, lead, zinc, crude oil, natural gas",
        "Governor_Name" => "Alexander Chioma Otti",
        "Population" => 4841943,
        "Landmass" => "6,320 km²",
        "Geopolitical_Zone" => "South East",
        "LGA" => 17,
        "Slogan" => "God's Own State"
    ],
    [
        "State_Name" => "Adamawa",
        "capital" => "Yola",
        "Mineral_Resources" => "gypsum, bentonite, kaolin, magnetite, iron, limestone",
        "Governor_Name" => "Ahmadu Umaru Fintiri",
        "Population" => 5236948,
        "Landmass" => "36,917 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 21,
        "Slogan" => "Land of Beauty"
    ],
    [
        "State_Name" => "Akwa Ibom",
        "capital" => "Uyo",
        "Mineral_Resources" => "Crude Oil, Natural Gas, limestone",
        "Governor_Name" => "Umo Bassey Eno",
        "Population" => 5780581,
        "Landmass" => "7,081 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 31,
        "Slogan" => "Land of Promise"
    ],
    [
        "State_Name" => "Anambra",
        "capital" => "Awka",
        "Mineral_Resources" => "Crude Oil, Natural Gas, Iron Ore, gypsum, limestone",
        "Governor_Name" => "Charles Chukwuma Soludo",
        "Population" => 7299910,
        "Landmass" => "4,844 km²",
        "Geopolitical_Zone" => "South East",
        "LGA" => 21,
        "Slogan" => "Light of the Nation"
    ],
    [
        "State_Name" => "Bauchi",
        "capital" => "Bauchi",
        "Mineral_Resources" => "Gold, coal, gypsum, kaolin",
        "Governor_Name" => "Bala Abdulkadir Mohammed",
        "Population" => 7540663,
        "Landmass" => "45,893 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 20,
        "Slogan" => "Pearl of Tourism"
    ],
    [
        "State_Name" => "Bayelsa",
        "capital" => "Yenagoa",
        "Mineral_Resources" => "Crude Oil, Natural Gas, Coal, Silica Sand",
        "Governor_Name" => "Douye Diri",
        "Population" => 2394725,
        "Landmass" => "10,773 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 8,
        "Slogan" => "Glory of All Lands"
    ],
    [
        "State_Name" => "Benue",
        "capital" => "Makurdi",
        "Mineral_Resources" => "limestone, coal, gypsum, zinc",
        "Governor_Name" => "Hyacinth Iormem Alia",
        "Population" => 6687706,
        "Landmass" => "34,059 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 23,
        "Slogan" => "Food Basket of the Nation"
    ],
    [
        "State_Name" => "Borno",
        "capital" => "Maiduguri",
        "Mineral_Resources" => "Clay, Iron Ore, Uranium, Silica Sand",
        "Governor_Name" => "Babagana Umara Zulum",
        "Population" => 6651590,
        "Landmass" => "70,898 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 27,
        "Slogan" => "Home of Peace"
    ],
    [
        "State_Name" => "Cross River",
        "capital" => "Calabar",
        "Mineral_Resources" => "Natural Gas, limestone, Iron Ore, Gold, Coal",
        "Governor_Name" => "Bassey Edet Otu",
        "Population" => 4175020,
        "Landmass" => "22,050 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 18,
        "Slogan" => "The People's Paradise"
    ],
    [
        "State_Name" => "Delta",
        "capital" => "Asaba",
        "Mineral_Resources" => "Natural Gas, Crude Oil, gypsum, Silica, Lignite",
        "Governor_Name" => "Sheriff Francis Orohwedor Oborevwori",
        "Population" => 6107543,
        "Landmass" => "17,698 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 25,
        "Slogan" => "The Big Heart"
    ],
    [
        "State_Name" => "Ebonyi",
        "capital" => "Abakaliki",
        "Mineral_Resources" => "Salt, Limestone, Granite",
        "Governor_Name" => "Francis Ogbonna Erishi Nwifuru",
        "Population" => 4007155,
        "Landmass" => "5,670 km²",
        "Geopolitical_Zone" => "South East",
        "LGA" => 13,
        "Slogan" => "Salt of the Nation"
    ],
    [
        "State_Name" => "Edo",
        "capital" => "Benin",
        "Mineral_Resources" => "Limestone, Marble, Gold, Bitumen",
        "Governor_Name" => "Monday Okpebholo",
        "Population" => 5527810,
        "Landmass" => "19,559 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 18,
        "Slogan" => "Heartbeat of the Nation"
    ],
    [
        "State_Name" => "Ekiti",
        "capital" => "Ado Ekiti",
        "Mineral_Resources" => "Kaolin, Granite, Columbite, Bauxite",
        "Governor_Name" => "Abiodun Abayomi Oyebanji",
        "Population" => 3398177,
        "Landmass" => "3,536 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 16,
        "Slogan" => "Land of Honour and Integrity"
    ],
    [
        "State_Name" => "Enugu",
        "capital" => "Enugu",
        "Mineral_Resources" => "Coal, Limestone, Iron Ore, Natural Gas",
        "Governor_Name" => "Dr Peter Mbah",
        "Population" => 5396098,
        "Landmass" => "7,161 km²",
        "Geopolitical_Zone" => "South East",
        "LGA" => 17,
        "Slogan" => "Coal City State"
    ],
    [
        "State_Name" => "Gombe",
        "capital" => "Gombe",
        "Mineral_Resources" => "Limestones, coal, gypsum, kaolin",
        "Governor_Name" => "Muhammad Inuwa Yahaya",
        "Population" => 4623462,
        "Landmass" => "18,768 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 17,
        "Slogan" => "Jewel in the Savannah"
    ],
    [
        "State_Name" => "Imo",
        "capital" => "Owerri",
        "Mineral_Resources" => "limestone, phosphate, gypsum",
        "Governor_Name" => "Hope Odidika Uzodimma",
        "Population" => 6067722,
        "Landmass" => "5,530 km²",
        "Geopolitical_Zone" => "South East",
        "LGA" => 27,
        "Slogan" => "Eastern Heartland"
    ],
    [
        "State_Name" => "Jigawa",
        "capital" => "Dutse",
        "Mineral_Resources" => "granite, kaolin, iron ore, tin",
        "Governor_Name" => "Umar Namadi",
        "Population" => 6979080,
        "Landmass" => "23,154 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 27,
        "Slogan" => "The New World"
    ],
    [
        "State_Name" => "Kaduna",
        "capital" => "Kaduna",
        "Mineral_Resources" => "gold, nickel, columbite, kaolin",
        "Governor_Name" => "Uba Sani",
        "Population" => 8324285,
        "Landmass" => "6,320 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 23,
        "Slogan" => "Centre of Learning"
    ],
    [
        "State_Name" => "Kano",
        "capital" => "Kano",
        "Mineral_Resources" => "caserite, copper, columbite",
        "Governor_Name" => "Abba Kabir Yusuf",
        "Population" => 16253549,
        "Landmass" => "20,131 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 44,
        "Slogan" => "Centre of Commerce"
    ],
    [
        "State_Name" => "Katsina",
        "capital" => "Katsina",
        "Mineral_Resources" => "kaolin, gold, asbestos, silica sand",
        "Governor_Name" => "Dikko Umar Radda",
        "Population" => 9300382,
        "Landmass" => "24,192 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 34,
        "Slogan" => "Home of Hospitality"
    ],
    [
        "State_Name" => "Kebbi",
        "capital" => "Birnin Kebbi",
        "Mineral_Resources" => "gold, lithium, limestone, manganese",
        "Governor_Name" => "Mohammed Nasir Idris",
        "Population" => 6001610,
        "Landmass" => "36,800 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 21,
        "Slogan" => "Land of Equity"
    ],
    [
        "State_Name" => "Kogi",
        "capital" => "Lokoja",
        "Mineral_Resources" => "Iron Ore, limestone, coal, gold",
        "Governor_Name" => "Ahmed Usman Ododo",
        "Population" => 5053734,
        "Landmass" => "29,833 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 21,
        "Slogan" => "The Confluence State"
    ],
    [
        "State_Name" => "Kwara",
        "capital" => "Ilorin",
        "Mineral_Resources" => "gold, marble, columbite, limestone",
        "Governor_Name" => "AbdulRahman AbdulRazaq",
        "Population" => 4841943,
        "Landmass" => "6,320 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 16,
        "Slogan" => "State of Harmony"
    ],
    [
        "State_Name" => "Lagos",
        "capital" => "Ikeja",
        "Mineral_Resources" => "Bitumen, clay, crude oil",
        "Governor_Name" => "Babajide Olusola Sanwo-Olu",
        "Population" => 15772884,
        "Landmass" => "3,577 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 20,
        "Slogan" => "Centre of Excellence"
    ],
    [
        "State_Name" => "Nasarawa",
        "capital" => "Lafia",
        "Mineral_Resources" => "lithium, gold, tin, columbite",
        "Governor_Name" => "Abdullahi Audu Sule",
        "Population" => 3632239,
        "Landmass" => "27,117 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 13,
        "Slogan" => "Home of Solid Minerals"
    ],
    [
        "State_Name" => "Niger",
        "capital" => "Minna",
        "Mineral_Resources" => "Uranium, Gold, coal, iron Ore",
        "Governor_Name" => "Mohammed Umar Bago",
        "Population" => 6720617,
        "Landmass" => "76,363 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 25,
        "Slogan" => "The Power State"
    ],
    [
        "State_Name" => "Ogun",
        "capital" => "Abeokuta",
        "Mineral_Resources" => "phosphate, granite, limestone, bitumen",
        "Governor_Name" => "Adedapo Oluseun Abiodun",
        "Population" => 6445275,
        "Landmass" => "16,762 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 20,
        "Slogan" => "Gateway state"
    ],
    [
        "State_Name" => "Ondo",
        "capital" => "Akure",
        "Mineral_Resources" => "Crude Oil, Natural Gas, bitumen, limestone",
        "Governor_Name" => "Lucky Orimisan Aiyedatiwa",
        "Population" => 5469707,
        "Landmass" => "15,500 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 18,
        "Slogan" => "Sunshine State"
    ],
    [
        "State_Name" => "Osun",
        "capital" => "Osogbo",
        "Mineral_Resources" => "Gold, Talc, Granite, Casserite",
        "Governor_Name" => "Ademola Nurudeen Jackson Adeleke",
        "Population" => 4237396,
        "Landmass" => "14,875 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 30,
        "Slogan" => "State of the Living Spring"
    ],
    [
        "State_Name" => "Oyo",
        "capital" => "Ibadan",
        "Mineral_Resources" => "Marble, Gold, Cassiterite, kaolin",
        "Governor_Name" => "Oluseyi Abiodun Makinde",
        "Population" => 7512855,
        "Landmass" => "28,454 km²",
        "Geopolitical_Zone" => "South West",
        "LGA" => 33,
        "Slogan" => "Pace-Setter State"
    ],
    [
        "State_Name" => "Plateau",
        "capital" => "Jos",
        "Mineral_Resources" => "Tin, Coal, Columbite, Marble",
        "Governor_Name" => "Caleb Manasseh Mutfwang",
        "Population" => 5400974,
        "Landmass" => "30,913 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 17,
        "Slogan" => "Home of Peace and Tourism"
    ],
    [
        "State_Name" => "Rivers",
        "capital" => "Port Harcourt",
        "Mineral_Resources" => "Crude oil, Natural Gas, silica, Clay",
        "Governor_Name" => "Siminalayi Fubara",
        "Population" => 7234973,
        "Landmass" => "11,017 km²",
        "Geopolitical_Zone" => "South South",
        "LGA" => 23,
        "Slogan" => "Treasure Base of the Nation"
    ],
    [
        "State_Name" => "Sokoto",
        "capital" => "Sokoto",
        "Mineral_Resources" => "Limestone, phosphate, gypsum, kaolin",
        "Governor_Name" => "Ahmad Aliyu Sokoto",
        "Population" => 6163187,
        "Landmass" => "25,973 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 23,
        "Slogan" => "Seat of the Caliphate"
    ],
    [
        "State_Name" => "Taraba",
        "capital" => "Jalingo",
        "Mineral_Resources" => "",
        "Governor_Name" => "Agbu Kefas",
        "Population" => 5400974,
        "Landmass" => "30,913 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 17,
        "Slogan" => "Nature's Gift to the Nation"
    ],
    [
        "State_Name" => "Yobe",
        "capital" => "Damaturu",
        "Mineral_Resources" => "gypsum, limestone, kaolin, silica sand",
        "Governor_Name" => "Mai Mala Buni",
        "Population" => 4350401,
        "Landmass" => "45,502 km²",
        "Geopolitical_Zone" => "North East",
        "LGA" => 17,
        "Slogan" => "Pride of the Sahel"
    ],
    [
        "State_Name" => "Zamfara",
        "capital" => "Gusau",
        "Mineral_Resources" => "gold, lithium, iron ore, lead, zinc",
        "Governor_Name" => "Dauda Lawal",
        "Population" => 5517793,
        "Landmass" => "39,762 km²",
        "Geopolitical_Zone" => "North West",
        "LGA" => 14,
        "Slogan" => "Farming is Our Pride"
    ],
    [
        "State_Name" => "FCT",
        "capital" => "Abuja",
        "Mineral_Resources" => "casserite, clay, gold, marble",
        "Governor_Name" => "Ezenwo Nyesom Wike",
        "Population" => 4892443,
        "Landmass" => "7,315 km²",
        "Geopolitical_Zone" => "North Central",
        "LGA" => 6,
        "Slogan" => "Centre of Unity"
    ]
];
